name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # jis branch se deploy karna hai

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: .  # Jis folder ko deploy karna hai, jaise ./dist ya . pura repo

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
